spring.application.name=ramcharitmanas

spring.datasource.url=jdbc:mysql://localhost:3306/ramcharitmanas

spring.datasource.username=root

spring.datasource.password=Admin_2008

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
